// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSBrrSH4jtQu7nRPWc-9CaTBEUFNtib8Y',
    appId: '1:828894103678:web:07dec2d87c03ebd20d302f',
    messagingSenderId: '828894103678',
    projectId: 'todo-cce89',
    authDomain: 'todo-cce89.firebaseapp.com',
    storageBucket: 'todo-cce89.appspot.com',
    measurementId: 'G-4EY2YC06EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ym4zbso4fN2ZdeTo91-8g87QOs8QGXM',
    appId: '1:828894103678:android:2919c221c5add08b0d302f',
    messagingSenderId: '828894103678',
    projectId: 'todo-cce89',
    storageBucket: 'todo-cce89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnCE_nhLMKyGM3zBM8tYfnjWM-BdrVJVo',
    appId: '1:828894103678:ios:b8543022d11d59830d302f',
    messagingSenderId: '828894103678',
    projectId: 'todo-cce89',
    storageBucket: 'todo-cce89.appspot.com',
    iosBundleId: 'com.example.toDo',
  );
}
